services:
  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: gradioBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio_app
    restart: always
    ports:
      - "7861:7860"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: gradioBD
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
      - media_volume:/app/media  # отдельный volume для медиа

volumes:
  postgres_data:
  media_volume:
